In [5]:
from mecon.data.data_management import CachedFileDataManager
from mecon.etl.dataset import Dataset
import pathlib
from mecon.app.current_data import WorkingDataManager
datasets_dir = pathlib.Path("/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets")#config.DEFAULT_DATASETS_DIR_PATH
dataset = Dataset.from_dirpath(datasets_dir / 'shared')
data_manager = CachedFileDataManager(dataset)
dataset

INFO:root:MECON_ROOT_DIRPATH not found in environment variables. Using default value relative to __file__='/Users/wimpole/PycharmProjects/mecon/mecon/config.py'.
INFO:root:MECON_ROOT_DIRPATH set to: MECON_ROOT_DIRPATH=PosixPath('/Users/wimpole/PycharmProjects/mecon')

DatasetV2(shared): /Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/shared

In [6]:
transactions = data_manager.get_transactions()
transactions.size()

7643

In [8]:
monzo = transactions.containing_tags('Monzo')
monzo.size()

2457

In [10]:
tags_involved = monzo.all_tags()
tags_involved

['Monzo',
 'All',
 'Spending',
 'MoneyOut',
 'Tap',
 'Afternoon',
 'Food',
 'Night',
 'Transfers',
 'Eating out',
 'MoneyIn',
 'My transfers',
 'Living costs',
 'Super Market',
 'Morning',
 'Commute',
 'Entertainment',
 'Drinks',
 'TFL',
 'Friends transfers',
 'BorisBike',
 'Online payments',
 'LimeBike',
 'Club',
 'Online orders',
 'Other bills',
 'Too good to go',
 'Rent',
 'Accomodation',
 'ITV income',
 'Income',
 'Alpha Bank',
 'GiffGaff',
 'Food delivery',
 'Flight tickets',
 'Train tickets',
 'Boat',
 'Uber Taxi',
 'Clothing',
 'Spotify']

In [4]:
import pandas as pd
old_calcs = pd.read_csv("/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/v2_dataset_test/data/current/calc_monitoring.csv", index_col=None)
new_calcs = pd.read_csv("/Users/wimpole/Library/CloudStorage/GoogleDrive-jimitsos41@gmail.com/Other computers/My Laptop/datasets/v2_dataset_test_monzo_api/data/current/calc_monitoring.csv", index_col=None)
old_calcs.shape, new_calcs.shape

((7643, 321), (7949, 321))

In [5]:
common_ids = set(old_calcs['id']).intersection(new_calcs['id'])
len(common_ids)

6315

In [6]:
common_cols = list(set(old_calcs.columns).intersection(set(new_calcs.columns)))
common_cols

['lower(description) contains cash',
 'lower(description) contains eating out',
 'lower(description) contains merieme katsani',
 'abs(amount) greater 34',
 'description contains EDF ENERGY-ECOM PLYMOUTH VIS',
 'split_comma(tags) in_csv Revolut,Monzo,HSBC',
 'description contains bank:HSBC, Amanmeet Singh Bha rent BP',
 'lower(description) contains drumshed',
 'lower(description) contains printworks',
 'lower(description) contains thames water',
 'lower(description) contains nando',
 'lower(description) contains mcdonald',
 'lower(description) contains blue star ferries',
 'str(datetime) greater 2023-04-06',
 'description contains bank:HSBCSVR',
 'lower(description) contains marsel katsani',
 'description contains bank:HSBC,',
 'lower(description) contains booking',
 'lower(description) contains tesco',
 'tags_added_1.8',
 'description contains Revolut**4562*',
 'lower(description) contains pophams',
 'description contains Dr Sina Motesharei rent BP',
 'hour(datetime) less 20',
 'lower(description) contains vision express',
 'lower(description) contains giffgaff',
 'lower(description) contains jetbrains',
 'amount',
 'tags_added_3.8',
 'lower(description) contains aldi',
 'currency equal EUR',
 'amount greater 80',
 'datetime.hour',
 'tags contains Spending',
 'lower(description) contains bank:monzo',
 'lower(description) contains wizz air',
 'hour(datetime) greater_equal 20',
 'lower(description) contains trainline',
 'upper(description) contains ELECTRIC BRIXTON',
 'description contains Dimitrios Kontzeda Sent from Revolut CR',
 'tags',
 'lower(description) contains jazz',
 'tags_list_3.8',
 'lower(description) contains ferry',
 'id',
 'lower(description) contains syn ka',
 'lower(description) contains polu poke',
 'split_comma(tags) in_csv Finallot Income',
 'tags_added_0.8',
 'tags not_contains Online payments',
 'lower(description) contains morrisons',
 'lower(description) contains lime',
 'tags contains Accomodation',
 'id in RVLTd20230523t140232an4550i33445,RVLTd20230617t141643ap18794i33942',
 'lower(description) contains samsung',
 'description contains To Dimitrios Kontzedakis',
 'lower(description) contains supersave',
 'description contains bank:INVENG',
 'lower(description) contains virgin media',
 'lower(description) contains zara',
 'lower(description) contains shacklewell',
 'lower(description) contains kontzeda',
 'lower(description) contains koinopraxia anek',
 'description contains DIMITRIS MONZO WEEKLY SO',
 'currency',
 'tags contains Airbnb',
 'id.none',
 'amount_cur',
 'lower(description) contains theodorouleas',
 'lower(description) contains british airways',
 'lower(description) contains tavern',
 'lower(description) contains kontzedaki d',
 'lower(description) contains poundland',
 'lower(description) contains hotel',
 'id in RVLTd20200824t164853an3051i3307,RVLTd20200824t110611an2391i3309',
 'lower(description) contains sainsbury',
 'lower(description) contains ally',
 'abs(amount) less 38',
 'lower(description) contains rose pub',
 'amount.none',
 'description contains ANALITIKA ONE',
 'tags contains Rent',
 'hour(datetime) less 8',
 'lower(description) contains amazon',
 'lower(description) contains stansted express',
 'description contains 🍸',
 'lower(description) contains fold',
 'upper(description) contains RESIDENT ADVISOR',
 'tags not_contains Therapy',
 'str(datetime) greater 2021-01-01',
 'amount equal 550',
 'tags not_contains BorisBike',
 'description contains bank:TRD212, action: Deposit',
 'tags contains Therapy',
 'lower(description) contains hostel',
 'lower(description) contains arms',
 'tags_list_2.8',
 'lower(description) contains masoutis',
 'split_comma(tags) in_csv Revolut',
 'split_comma(tags) in_csv ITV income',
 'lower(description) contains budgetair',
 'tags contains Too good to go',
 'currency.none',
 'lower(description) contains supermarket',
 'description contains Top-Up by *0852',
 'lower(description) contains anek lines',
 'abs(amount) greater 25',
 'split_comma(tags) in_csv My transfers,Alpha Bank,Friends transfers,Currency exchange,Home Bills,Rent',
 'lower(description) contains santander cycles',
 'lower(description) contains elif food',
 'upper(description) contains WWW.HP.COM',
 'lower(description) contains ryanair',
 'lower(description) contains karamanos',
 'lower(description) not_contains cash sainsby',
 'lower(description) contains deli ',
 'description',
 'amount equal 575',
 'lower(description) contains stefano di tommaso',
 'split_comma(tags) in_csv Monzo',
 'amount greater_equal 600',
 'description.upper',
 'upper(description) contains IGBONS',
 'tags contains Online orders',
 'lower(description) contains dream bags',
 'amount less 0',
 'description contains Kontzedakis',
 'lower(description) contains easyjet',
 'tags contains Flight tickets',
 'lower(description) contains fabric',
 'datetime.str',
 'split_comma(tags) in_csv Eating out',
 'amount greater_equal 400',
 'description.lower',
 'tags contains Income',
 'description contains Dimitrios Kontzeda Sent from Monzo CR',
 'id not_contains TRD212d20250211t163510ap364274i7',
 'description contains Payment from Kontzedaki',
 'lower(description) contains ebay',
 'lower(description) contains eat',
 'lower(description) not_contains netflix',
 'lower(description) contains lidl',
 'lower(description) contains exarchou',
 'lower(description) contains sakkadakis',
 'lower(description) contains lexington',
 'lower(description) contains bank:revolut',
 'lower(description) contains sideris',
 'lower(description) contains toogoodtog',
 'split_comma(tags) in_csv Super Market',
 'lower(tags) contains giffgaff',
 'lower(description) contains egg london',
 'lower(description) contains co-op',
 'lower(description) contains supermercats',
 'lower(description) contains nisa',
 'description contains EDF',
 'split_comma(tags) in_csv Home Bills',
 'split_comma(tags) in_csv Rent',
 'lower(description) contains exchange',
 'lower(description) not_contains cash at tesco',
 'amount.abs',
 'abs(amount) less 28',
 'lower(description) contains spencer',
 'lower(description) contains asos',
 'lower(description) contains galaxias',
 'lower(description) contains just',
 'amount equal 600',
 'lower(description) contains dimitri',
 'upper(description) contains DELOITTE LLP CR',
 'description contains 🍺',
 'lower(description) contains syn.ka',
 'split_comma(tags) in_csv Deloitte income',
 'lower(description) contains karimpidis',
 'lower(description) contains duke',
 'amount less -40',
 'lower(description) contains from georgios',
 'abs(amount) greater 30',
 'description contains To Dimitrios (Alpha) Kontzedakis',
 'lower(description) contains efood',
 'lower(description) contains advanced optical',
 'split_comma(tags) in_csv HSBC',
 'lower(description) contains tfl cycle hire',
 'lower(description) contains amznmktplace',
 'lower(description) contains tfl',
 'description contains bank:TRD212',
 'lower(description) contains eleni exarchou',
 'upper(description) contains VILLAGE 512',
 'hour(datetime) less 12',
 'split_comma(tags) in_csv TFL,BorisBike,LimeBike,Uber Taxi',
 'lower(description) contains joseph',
 'lower(description) contains marks',
 'lower(description) contains spotify',
 'lower(description) contains jago',
 'lower(tags) contains spotify',
 'lower(description) contains 110 pennington street',
 'amount equal 450',
 'lower(description) contains h&m',
 'tags_added_2.8',
 'str(datetime) greater 2023-01-10',
 'lower(description) contains asda',
 'lower(description) contains sky express',
 'tags_list_0.8',
 'id in RVLTd20200821t110751an22000i3306',
 'lower(description) contains category: entertainment',
 'tags_list_1.8',
 'tags not_contains Income',
 'upper(description) contains GRADY ALWYNE',
 'lower(description) contains transfer',
 'amount greater 0',
 'id in RVLTd20220810t190439an57500i32748,RVLTd20220810t211424an57500i32752,RVLTd20220810t190500an75000i32749,RVLTd20230421t094803an40000i33395,RVLTd20230301t141958an38000i33320,RVLTd20220810t190439an57500i32747, RVLTd20200106t181345an50000i36, MZNd20200203t133216an40000itx_00009rf6iRCr2zJCr2zTEH, RVLTd20200203t132435an25349i354, RVLTd20200203t140951an10349i355, MZNd20200301t011821an40000itx_00009sY15bSTBTrWFgzFIH, MZNd20200302t200328an20000itx_00009sbi0yOVMNPxgVKsFt, MZNd20200302t200239an10000itx_00009sbhwQv1sYDESh6CFl, RVLTd20200327t194415an7000i374',
 'upper(description) contains THE CURRENCY CLOUD LTD',
 'hour(datetime) greater_equal 12',
 'upper(description) contains PEACHEY',
 'lower(description) contains vasilopoulos',
 'lower(description) contains paypal',
 'lower(description) contains cosmote',
 'lower(description) contains olympic',
 'description contains INSTABOOK LTD',
 'datetime',
 'tags not_contains Transfer',
 'tags contains Revolut',
 'description contains DIMITRIOS KONTZEDA TO REVOLUT SO',
 'lower(description) contains kiwi.com',
 'description.none',
 'lower(description) contains michail',
 'lower(description) contains uber',
 'lower(description) contains urban outfitters',
 'lower(description) contains restaurant',
 'str(datetime) less 2023-04-07',
 'lower(description) contains from eleni exarchou',
 'lower(description) contains kfc',
 'lower(description) contains category: eating out',
 'upper(description) contains TYPE: TRANSFER',
 'lower(description) contains e food',
 'lower(description) contains bulb energy',
 'tags contains Food delivery',
 'amount greater 2000',
 'amount less 0.0',
 'hour(datetime) greater_equal 8',
 'old_tags',
 'upper(description) contains MY REVO',
 'lower(description) contains brewpub',
 'tags contains Monzo',
 'lower(description) not_contains eat',
 'lower(description) contains airbnb',
 'lower(description) contains sklavenitis',
 'upper(description) contains VILLAGE UNDERGROUND',
 'new_tags_list',
 'description contains ITV',
 'lower(description) contains fragkiadakis',
 'lower(description) contains waitrose']

In [7]:
fields = ['amount', 'datetime', 'description', 'amount_cur', 'currency', 'tags']

cols_of_interest = common_cols.copy()

for col in common_cols:
    for field in fields:
        if col == field:
            print(f"REMOVED: column '{col}' is field")
            cols_of_interest.remove(col)
            break
        elif col.startswith(field+'.'):
            print(f"REMOVED: column '{col}' is transformation")
            cols_of_interest.remove(col)
            break
        elif col.startswith('tags_list'):
            print(f"REMOVED: column '{col}' is tags_list")
            cols_of_interest.remove(col)
            break
        # else:
        #    print(f"ADDED: column {col} is VALID")
cols_of_interest

REMOVED: column 'amount' is field
REMOVED: column 'datetime.hour' is transformation
REMOVED: column 'tags' is field
REMOVED: column 'tags_list_3.8' is tags_list
REMOVED: column 'currency' is field
REMOVED: column 'amount_cur' is field
REMOVED: column 'amount.none' is transformation
REMOVED: column 'tags_list_2.8' is tags_list
REMOVED: column 'currency.none' is transformation
REMOVED: column 'description' is field
REMOVED: column 'description.upper' is transformation
REMOVED: column 'datetime.str' is transformation
REMOVED: column 'description.lower' is transformation
REMOVED: column 'amount.abs' is transformation
REMOVED: column 'tags_list_0.8' is tags_list
REMOVED: column 'tags_list_1.8' is tags_list
REMOVED: column 'datetime' is field
REMOVED: column 'description.none' is transformation

['lower(description) contains cash',
 'lower(description) contains eating out',
 'lower(description) contains merieme katsani',
 'abs(amount) greater 34',
 'description contains EDF ENERGY-ECOM PLYMOUTH VIS',
 'split_comma(tags) in_csv Revolut,Monzo,HSBC',
 'description contains bank:HSBC, Amanmeet Singh Bha rent BP',
 'lower(description) contains drumshed',
 'lower(description) contains printworks',
 'lower(description) contains thames water',
 'lower(description) contains nando',
 'lower(description) contains mcdonald',
 'lower(description) contains blue star ferries',
 'str(datetime) greater 2023-04-06',
 'description contains bank:HSBCSVR',
 'lower(description) contains marsel katsani',
 'description contains bank:HSBC,',
 'lower(description) contains booking',
 'lower(description) contains tesco',
 'tags_added_1.8',
 'description contains Revolut**4562*',
 'lower(description) contains pophams',
 'description contains Dr Sina Motesharei rent BP',
 'hour(datetime) less 20',
 'lower(description) contains vision express',
 'lower(description) contains giffgaff',
 'lower(description) contains jetbrains',
 'tags_added_3.8',
 'lower(description) contains aldi',
 'currency equal EUR',
 'amount greater 80',
 'tags contains Spending',
 'lower(description) contains bank:monzo',
 'lower(description) contains wizz air',
 'hour(datetime) greater_equal 20',
 'lower(description) contains trainline',
 'upper(description) contains ELECTRIC BRIXTON',
 'description contains Dimitrios Kontzeda Sent from Revolut CR',
 'lower(description) contains jazz',
 'lower(description) contains ferry',
 'id',
 'lower(description) contains syn ka',
 'lower(description) contains polu poke',
 'split_comma(tags) in_csv Finallot Income',
 'tags_added_0.8',
 'tags not_contains Online payments',
 'lower(description) contains morrisons',
 'lower(description) contains lime',
 'tags contains Accomodation',
 'id in RVLTd20230523t140232an4550i33445,RVLTd20230617t141643ap18794i33942',
 'lower(description) contains samsung',
 'description contains To Dimitrios Kontzedakis',
 'lower(description) contains supersave',
 'description contains bank:INVENG',
 'lower(description) contains virgin media',
 'lower(description) contains zara',
 'lower(description) contains shacklewell',
 'lower(description) contains kontzeda',
 'lower(description) contains koinopraxia anek',
 'description contains DIMITRIS MONZO WEEKLY SO',
 'tags contains Airbnb',
 'id.none',
 'lower(description) contains theodorouleas',
 'lower(description) contains british airways',
 'lower(description) contains tavern',
 'lower(description) contains kontzedaki d',
 'lower(description) contains poundland',
 'lower(description) contains hotel',
 'id in RVLTd20200824t164853an3051i3307,RVLTd20200824t110611an2391i3309',
 'lower(description) contains sainsbury',
 'lower(description) contains ally',
 'abs(amount) less 38',
 'lower(description) contains rose pub',
 'description contains ANALITIKA ONE',
 'tags contains Rent',
 'hour(datetime) less 8',
 'lower(description) contains amazon',
 'lower(description) contains stansted express',
 'description contains 🍸',
 'lower(description) contains fold',
 'upper(description) contains RESIDENT ADVISOR',
 'tags not_contains Therapy',
 'str(datetime) greater 2021-01-01',
 'amount equal 550',
 'tags not_contains BorisBike',
 'description contains bank:TRD212, action: Deposit',
 'tags contains Therapy',
 'lower(description) contains hostel',
 'lower(description) contains arms',
 'lower(description) contains masoutis',
 'split_comma(tags) in_csv Revolut',
 'split_comma(tags) in_csv ITV income',
 'lower(description) contains budgetair',
 'tags contains Too good to go',
 'lower(description) contains supermarket',
 'description contains Top-Up by *0852',
 'lower(description) contains anek lines',
 'abs(amount) greater 25',
 'split_comma(tags) in_csv My transfers,Alpha Bank,Friends transfers,Currency exchange,Home Bills,Rent',
 'lower(description) contains santander cycles',
 'lower(description) contains elif food',
 'upper(description) contains WWW.HP.COM',
 'lower(description) contains ryanair',
 'lower(description) contains karamanos',
 'lower(description) not_contains cash sainsby',
 'lower(description) contains deli ',
 'amount equal 575',
 'lower(description) contains stefano di tommaso',
 'split_comma(tags) in_csv Monzo',
 'amount greater_equal 600',
 'upper(description) contains IGBONS',
 'tags contains Online orders',
 'lower(description) contains dream bags',
 'amount less 0',
 'description contains Kontzedakis',
 'lower(description) contains easyjet',
 'tags contains Flight tickets',
 'lower(description) contains fabric',
 'split_comma(tags) in_csv Eating out',
 'amount greater_equal 400',
 'tags contains Income',
 'description contains Dimitrios Kontzeda Sent from Monzo CR',
 'id not_contains TRD212d20250211t163510ap364274i7',
 'description contains Payment from Kontzedaki',
 'lower(description) contains ebay',
 'lower(description) contains eat',
 'lower(description) not_contains netflix',
 'lower(description) contains lidl',
 'lower(description) contains exarchou',
 'lower(description) contains sakkadakis',
 'lower(description) contains lexington',
 'lower(description) contains bank:revolut',
 'lower(description) contains sideris',
 'lower(description) contains toogoodtog',
 'split_comma(tags) in_csv Super Market',
 'lower(tags) contains giffgaff',
 'lower(description) contains egg london',
 'lower(description) contains co-op',
 'lower(description) contains supermercats',
 'lower(description) contains nisa',
 'description contains EDF',
 'split_comma(tags) in_csv Home Bills',
 'split_comma(tags) in_csv Rent',
 'lower(description) contains exchange',
 'lower(description) not_contains cash at tesco',
 'abs(amount) less 28',
 'lower(description) contains spencer',
 'lower(description) contains asos',
 'lower(description) contains galaxias',
 'lower(description) contains just',
 'amount equal 600',
 'lower(description) contains dimitri',
 'upper(description) contains DELOITTE LLP CR',
 'description contains 🍺',
 'lower(description) contains syn.ka',
 'split_comma(tags) in_csv Deloitte income',
 'lower(description) contains karimpidis',
 'lower(description) contains duke',
 'amount less -40',
 'lower(description) contains from georgios',
 'abs(amount) greater 30',
 'description contains To Dimitrios (Alpha) Kontzedakis',
 'lower(description) contains efood',
 'lower(description) contains advanced optical',
 'split_comma(tags) in_csv HSBC',
 'lower(description) contains tfl cycle hire',
 'lower(description) contains amznmktplace',
 'lower(description) contains tfl',
 'description contains bank:TRD212',
 'lower(description) contains eleni exarchou',
 'upper(description) contains VILLAGE 512',
 'hour(datetime) less 12',
 'split_comma(tags) in_csv TFL,BorisBike,LimeBike,Uber Taxi',
 'lower(description) contains joseph',
 'lower(description) contains marks',
 'lower(description) contains spotify',
 'lower(description) contains jago',
 'lower(tags) contains spotify',
 'lower(description) contains 110 pennington street',
 'amount equal 450',
 'lower(description) contains h&m',
 'tags_added_2.8',
 'str(datetime) greater 2023-01-10',
 'lower(description) contains asda',
 'lower(description) contains sky express',
 'id in RVLTd20200821t110751an22000i3306',
 'lower(description) contains category: entertainment',
 'tags not_contains Income',
 'upper(description) contains GRADY ALWYNE',
 'lower(description) contains transfer',
 'amount greater 0',
 'id in RVLTd20220810t190439an57500i32748,RVLTd20220810t211424an57500i32752,RVLTd20220810t190500an75000i32749,RVLTd20230421t094803an40000i33395,RVLTd20230301t141958an38000i33320,RVLTd20220810t190439an57500i32747, RVLTd20200106t181345an50000i36, MZNd20200203t133216an40000itx_00009rf6iRCr2zJCr2zTEH, RVLTd20200203t132435an25349i354, RVLTd20200203t140951an10349i355, MZNd20200301t011821an40000itx_00009sY15bSTBTrWFgzFIH, MZNd20200302t200328an20000itx_00009sbi0yOVMNPxgVKsFt, MZNd20200302t200239an10000itx_00009sbhwQv1sYDESh6CFl, RVLTd20200327t194415an7000i374',
 'upper(description) contains THE CURRENCY CLOUD LTD',
 'hour(datetime) greater_equal 12',
 'upper(description) contains PEACHEY',
 'lower(description) contains vasilopoulos',
 'lower(description) contains paypal',
 'lower(description) contains cosmote',
 'lower(description) contains olympic',
 'description contains INSTABOOK LTD',
 'tags not_contains Transfer',
 'tags contains Revolut',
 'description contains DIMITRIOS KONTZEDA TO REVOLUT SO',
 'lower(description) contains kiwi.com',
 'lower(description) contains michail',
 'lower(description) contains uber',
 'lower(description) contains urban outfitters',
 'lower(description) contains restaurant',
 'str(datetime) less 2023-04-07',
 'lower(description) contains from eleni exarchou',
 'lower(description) contains kfc',
 'lower(description) contains category: eating out',
 'upper(description) contains TYPE: TRANSFER',
 'lower(description) contains e food',
 'lower(description) contains bulb energy',
 'tags contains Food delivery',
 'amount greater 2000',
 'amount less 0.0',
 'hour(datetime) greater_equal 8',
 'old_tags',
 'upper(description) contains MY REVO',
 'lower(description) contains brewpub',
 'tags contains Monzo',
 'lower(description) not_contains eat',
 'lower(description) contains airbnb',
 'lower(description) contains sklavenitis',
 'upper(description) contains VILLAGE UNDERGROUND',
 'new_tags_list',
 'description contains ITV',
 'lower(description) contains fragkiadakis',
 'lower(description) contains waitrose']

In [8]:
old = old_calcs[old_calcs['id'].isin(common_ids)].sort_values('id')[cols_of_interest].reset_index(drop=True)
new = new_calcs[new_calcs['id'].isin(common_ids)].sort_values('id')[cols_of_interest].reset_index(drop=True)
old.shape, new.shape

((6315, 231), (6315, 231))

In [9]:
# old['tags'] = old['tags'].apply(lambda s:set(s.split(',')))
# new['tags'] = new['tags'].apply(lambda s:set(s.split(',')))
# (old['tags'] == new['tags']).sum()

In [10]:
comps = old.compare(new)
# comps.columns = [c[0]+' ('+('old' if c[1]=='self' else 'new')+')' for c in comps.columns]
# cols = list({c for c in comps.columns})
cols = list({c[0] for c in comps.columns})

comps['id'] = old['id']
comps

     lower(description) contains cash        \
                                 self other
0                                 NaN   NaN
1                                 NaN   NaN
2                                 NaN   NaN
3                                 NaN   NaN
4                                 NaN   NaN
...                               ...   ...
6310                              NaN   NaN
6311                              NaN   NaN
6312                              NaN   NaN
6313                              NaN   NaN
6314                              NaN   NaN

     lower(description) contains eating out       tags_added_1.8        \
                                       self other           self other
0                                       NaN   NaN            NaN   NaN
1                                       NaN   NaN            NaN   NaN
2                                       NaN   NaN            NaN   NaN
3                                       NaN   NaN            NaN   NaN
4                                       NaN   NaN            NaN   NaN
...                                     ...   ...            ...   ...
6310                                    NaN   NaN            NaN   NaN
6311                                    NaN   NaN            NaN   NaN
6312                                    NaN   NaN            NaN   NaN
6313                                    NaN   NaN            NaN   NaN
6314                                    NaN   NaN            NaN   NaN

     tags_added_3.8       tags_added_0.8        ...  \
               self other           self other  ...
0               NaN   NaN            NaN   NaN  ...
1               NaN   NaN            NaN   NaN  ...
2               NaN   NaN            NaN   NaN  ...
3               NaN   NaN            NaN   NaN  ...
4               NaN   NaN            NaN   NaN  ...
...             ...   ...            ...   ...  ...
6310            NaN   NaN            NaN   NaN  ...
6311            NaN   NaN            NaN   NaN  ...
6312            NaN   NaN            NaN   NaN  ...
6313            NaN   NaN            NaN   NaN  ...
6314            NaN   NaN            NaN   NaN  ...

     lower(description) contains category: eating out  \
                                                other
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
...                                               ...
6310                                              NaN
6311                                              NaN
6312                                              NaN
6313                                              NaN
6314                                              NaN

     tags contains Food delivery        \
                            self other
0                            NaN   NaN
1                            NaN   NaN
2                            NaN   NaN
3                            NaN   NaN
4                            NaN   NaN
...                          ...   ...
6310                         NaN   NaN
6311                         NaN   NaN
6312                         NaN   NaN
6313                         NaN   NaN
6314                         NaN   NaN

                                               old_tags        \
                                                   self other
0     HSBC Savings,MoneyIn,Night,My transfers,Spendi...   NaN
1               HSBC Savings,MoneyIn,Night,Spending,All   NaN
2               HSBC Savings,MoneyIn,Night,Spending,All   NaN
3               HSBC Savings,MoneyIn,Night,Spending,All   NaN
4               HSBC Savings,MoneyIn,Night,Spending,All   NaN
...                                                 ...   ...
6310  MoneyIn,Night,Trading212,My transfers,Spending...   NaN
6311  Afternoon,MoneyIn,Trading212,My transfers,Spen...   NaN
6312         Afternoon,MoneyOut,Trading212,Spending,All   NaN
6313          Afternoon,MoneyIn,Trading212,Spending,All   NaN
6314  MoneyIn,Night,Trading212,My transfers,Spending...   NaN

     lower(description) not_contains eat       new_tags_list        \
                                    self other          self other
0                                    NaN   NaN           NaN   NaN
1                                    NaN   NaN           NaN   NaN
2                                    NaN   NaN           NaN   NaN
3                                    NaN   NaN           NaN   NaN
4                                    NaN   NaN           NaN   NaN
...                                  ...   ...           ...   ...
6310                                 NaN   NaN           NaN   NaN
6311                                 NaN   NaN           NaN   NaN
6312                                 NaN   NaN           NaN   NaN
6313                                 NaN   NaN           NaN   NaN
6314                                 NaN   NaN           NaN   NaN

                                       id

0     HSBCSVRd20240802t000000ap1000000i12
1        HSBCSVRd20240901t000000ap1629i10
2        HSBCSVRd20240901t000000ap1629i11
3         HSBCSVRd20241001t000000ap1634i8
4         HSBCSVRd20241001t000000ap1634i9
...                                   ...
6310      TRD212d20250122t204008ap50000i4
6311      TRD212d20250205t143909ap50000i5
6312     TRD212d20250207t191424an264274i6
6313     TRD212d20250211t163510ap364274i7
6314     TRD212d20250221t221635ap100000i8

[6315 rows x 57 columns]

In [11]:
# cols = comps.columns
# cols = list({c[0] for c in comps.columns})
cols

['split_comma(tags) in_csv TFL,BorisBike,LimeBike,Uber Taxi',
 'lower(description) contains cash',
 'lower(description) contains eating out',
 'tags_added_2.8',
 'split_comma(tags) in_csv Eating out',
 'lower(description) contains category: entertainment',
 'lower(description) contains eat',
 'lower(description) contains transfer',
 'lower(description) contains lidl',
 'lower(description) contains hotel',
 'lower(description) contains ally',
 'tags_added_1.8',
 'split_comma(tags) in_csv Super Market',
 'tags not_contains Transfer',
 'lower(description) contains uber',
 'lower(description) contains restaurant',
 'tags_added_3.8',
 'lower(description) contains kfc',
 'lower(description) contains category: eating out',
 'lower(description) contains arms',
 'tags contains Food delivery',
 'lower(description) contains supermarket',
 'old_tags',
 'split_comma(tags) in_csv My transfers,Alpha Bank,Friends transfers,Currency exchange,Home Bills,Rent',
 'lower(description) not_contains eat',
 'tags_added_0.8',
 'new_tags_list',
 'lower(description) contains tfl']

In [12]:
def get_col(col):
    res = comps[~comps[col].isna().any(axis=1)][['id', col]]
    res.columns = ['id', 'old', 'new']
    res['column'] = col
    res['count'] = len(res)
    return res

get_col(cols[1])

,id,old,new,column,count
997,MZNd20200203t133216an40000itx_00009rf6iRCr2zJC...,False,True,lower(description) contains cash,17
999,MZNd20200203t135813an10000itx_00009rf91yUbiIOO...,False,True,lower(description) contains cash,17
1006,MZNd20200206t195159an0itx_00009rls93fUWyi4uHLjKE,False,True,lower(description) contains cash,17
1007,MZNd20200206t195213an4000itx_00009rlsAKLM1CAwT...,False,True,lower(description) contains cash,17
1077,MZNd20200301t011821an40000itx_00009sY15bSTBTrW...,False,True,lower(description) contains cash,17
1082,MZNd20200302t200201an0itx_00009sbhsyDM925V2rNQrh,False,True,lower(description) contains cash,17
1083,MZNd20200302t200239an10000itx_00009sbhwQv1sYDE...,False,True,lower(description) contains cash,17
1084,MZNd20200302t200328an20000itx_00009sbi0yOVMNPx...,False,True,lower(description) contains cash,17
1104,MZNd20200307t220333an2000itx_00009smFIiEvOu98a...,False,True,lower(description) contains cash,17
1138,MZNd20200321t215135an3000itx_00009tFFQSh8iNQam...,False,True,lower(description) contains cash,17
1321,MZNd20230217t204135an3000itx_0000ASmXMWukujMFn...,False,True,lower(description) contains cash,17
1429,MZNd20231030t141022an2000itx_0000AbIXTFxCxVsHj...,False,True,lower(description) contains cash,17
1884,MZNd20241205t220252an0itx_0000AokUC3VVixqRrFgndD,False,True,lower(description) contains cash,17
1886,MZNd20241205t220350an0itx_0000AokUHR2Jfg3yW34q6j,False,True,lower(description) contains cash,17
1887,MZNd20241205t220405an8000itx_0000AokUIkuLH87xa...,False,True,lower(description) contains cash,17
1895,MZNd20241207t044249an0itx_0000Aon8Ox9B4FtSUeIRWb,False,True,lower(description) contains cash,17
1897,MZNd20241207t044330an2000itx_0000Aon8SdJKlBeMk...,False,True,lower(description) contains cash,17

In [13]:
all_diffs = pd.concat([get_col(col) for col in set(cols).difference(['id'])]).sort_values('count', ascending=False)
all_diffs

,id,old,new,column,count
1846,MZNd20241124t155659an2136itx_0000AoN9t3wJQT7nc...,False,True,lower(description) contains eat,877
2049,MZNd20250119t160333an1099itx_0000AqFFFNZQ9pxxQ...,False,True,lower(description) contains eat,877
2041,MZNd20250116t193104ap2000itx_0000Aq9KE6HmGm0Tk...,False,True,lower(description) contains eat,877
2042,MZNd20250116t193111an2026itx_0000Aq9KEiUAFADGE...,False,True,lower(description) contains eat,877
2043,MZNd20250118t143633an670itx_0000AqD2y7ZwlyvIgP...,False,True,lower(description) contains eat,877
...,...,...,...,...,...
2022,MZNd20250109t113848an260itx_0000Apu8TpklOJrBMP...,False,True,lower(description) contains uber,1
1523,MZNd20231216t222658an1200itx_0000AcsfwI1UBYA8Y...,"['All', 'Tap']",['All'],tags_added_3.8,1
2052,MZNd20250120t123831an270itx_0000AqH1Sljub8v9kZ...,False,True,lower(description) contains arms,1
1101,MZNd20200307t170556an4650itx_00009slojvB6hqg5R...,False,True,lower(description) contains lidl,1
1101,MZNd20200307t170556an4650itx_00009slojvB6hqg5R...,False,True,split_comma(tags) in_csv Super Market,1

In [14]:
comb_transactions = old_calcs[['id']+fields].add_prefix('old_').merge(new_calcs[['id']+fields].add_prefix('new_'), left_on='old_id', right_on='new_id')
comb_transactions['id'] = comb_transactions['old_id']
del comb_transactions['old_id'], comb_transactions['new_id']
comb_transactions

,old_amount,old_datetime,old_description,old_amount_cur,old_currency,old_tags,new_amount,new_datetime,new_description,new_amount_cur,new_currency,new_tags,id
0,8.333333,2019-02-27 15:03:15,"bank:Revolut, type: TRANSFER, product: Current...",10.00,EUR,"Afternoon,Friends transfers,MoneyIn,Revolut,My...",8.333333,2019-02-27 15:03:15,"bank:Revolut, type: TRANSFER, product: Current...",10.00,EUR,"Afternoon,Friends transfers,MoneyIn,Revolut,My...",RVLTd20190227t150315ap833i3634
1,-8.333333,2019-02-27 15:08:11,"bank:Revolut, type: TRANSFER, product: Current...",-10.00,EUR,"Afternoon,Friends transfers,MoneyOut,Revolut,M...",-8.333333,2019-02-27 15:08:11,"bank:Revolut, type: TRANSFER, product: Current...",-10.00,EUR,"Afternoon,Friends transfers,MoneyOut,Revolut,M...",RVLTd20190227t150811an833i3635
2,6.666667,2019-04-11 09:06:18,"bank:Revolut, type: TOPUP, product: Current, c...",8.00,EUR,"Alpha Bank,MoneyIn,Morning,Revolut,My transfer...",6.666667,2019-04-11 09:06:18,"bank:Revolut, type: TOPUP, product: Current, c...",8.00,EUR,"Alpha Bank,MoneyIn,Morning,Revolut,My transfer...",RVLTd20190411t090618ap666i3636
3,-4.850000,2019-04-13 18:06:40,"bank:Revolut, type: CARD_PAYMENT, product: Cur...",-5.82,EUR,"Afternoon,GiffGaff,MoneyOut,Revolut,Other bill...",-4.850000,2019-04-13 18:06:40,"bank:Revolut, type: CARD_PAYMENT, product: Cur...",-5.82,EUR,"Afternoon,GiffGaff,MoneyOut,Revolut,Other bill...",RVLTd20190413t180640an485i3637
4,-0.966667,2019-04-25 10:06:35,"bank:Revolut, type: TRANSFER, product: Current...",-1.16,EUR,"Alpha Bank,MoneyOut,Morning,Revolut,My transfe...",-0.966667,2019-04-25 10:06:35,"bank:Revolut, type: TRANSFER, product: Current...",-1.16,EUR,"Alpha Bank,MoneyOut,Morning,Revolut,My transfe...",RVLTd20190425t100635an96i3638
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6310,-25.140000,2025-02-03 20:21:36,"bank:Monzo, type: Card payment, name: Lidl, em...",-25.14,GBP,"MoneyOut,Monzo,Night,Super Market,Food,Living ...",-25.140000,2025-02-03 20:21:36,"bank:MonzoAPI, other_fields: {merchant_feedbac...",-25.14,GBP,"MoneyOut,Monzo,Night,Super Market,Food,Living ...",MZNd20250203t202136an2514itx_0000Aqkhz36zNJ4iA...
6311,500.000000,2025-02-05 14:39:09,"bank:TRD212, action: Deposit, notes: Transacti...",500.00,GBP,"Afternoon,MoneyIn,Trading212,My transfers,Spen...",500.000000,2025-02-05 14:39:09,"bank:TRD212, action: Deposit, notes: Transacti...",500.00,GBP,"Afternoon,MoneyIn,Trading212,My transfers,Spen...",TRD212d20250205t143909ap50000i5
6312,-2642.740000,2025-02-07 19:14:24,"bank:TRD212, action: Withdrawal, raw_id: 8ea50...",-2642.74,GBP,"Afternoon,MoneyOut,Trading212,Spending,All",-2642.740000,2025-02-07 19:14:24,"bank:TRD212, action: Withdrawal, raw_id: 8ea50...",-2642.74,GBP,"Afternoon,MoneyOut,Trading212,Spending,All",TRD212d20250207t191424an264274i6
6313,3642.740000,2025-02-11 16:35:10,"bank:TRD212, action: Deposit, raw_id: 76b170f5...",3642.74,GBP,"Afternoon,MoneyIn,Trading212,Spending,All",3642.740000,2025-02-11 16:35:10,"bank:TRD212, action: Deposit, raw_id: 76b170f5...",3642.74,GBP,"Afternoon,MoneyIn,Trading212,Spending,All",TRD212d20250211t163510ap364274i7
6314,1000.000000,2025-02-21 22:16:35,"bank:TRD212, action: Deposit, notes: Transacti...",1000.00,GBP,"MoneyIn,Night,Trading212,My transfers,Spending...",1000.000000,2025-02-21 22:16:35,"bank:TRD212, action: Deposit, notes: Transacti...",1000.00,GBP,"MoneyIn,Night,Trading212,My transfers,Spending...",TRD212d20250221t221635ap100000i8

In [17]:
all_diffs[all_diffs['column']=='lower(description) contains eat'].merge(comb_transactions[['id', 'old_description', 'new_description']], on='id')

,id,old,new,column,count,old_description,new_description
0,MZNd20241124t155659an2136itx_0000AoN9t3wJQT7nc...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Card payment, name: Willows,...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
1,MZNd20250119t160333an1099itx_0000AqFFFNZQ9pxxQ...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Card payment, name: Barrys F...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
2,MZNd20250116t193104ap2000itx_0000Aq9KE6HmGm0Tk...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Faster payment, name: KONTZE...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
3,MZNd20250116t193111an2026itx_0000Aq9KEiUAFADGE...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Card payment, name: Lidl, em...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
4,MZNd20250118t143633an670itx_0000AqD2y7ZwlyvIgP...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Card payment, name: Tesco, e...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
...,...,...,...,...,...,...,...
872,MZNd20230207t140457an1250itx_0000ASREpNmBzRNSu...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Card payment, name: Transpor...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
873,MZNd20230205t162157an509itx_0000ASNI1fsq14roNz...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Card payment, name: Ally S W...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
874,MZNd20230206t122729an0itx_0000ASP1c8x26w7GvCaREn,False,True,lower(description) contains eat,877,"bank:Monzo, type: Card payment, name: Google, ...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
875,MZNd20230206t122906ap8000itx_0000ASP1lAFodUaqY...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Faster payment, name: Dimitr...","bank:MonzoAPI, other_fields: {merchant_feedbac..."
876,MZNd20230205t144131an1998itx_0000ASN93zKZmc7GY...,False,True,lower(description) contains eat,877,"bank:Monzo, type: Card payment, name: Traid - ...","bank:MonzoAPI, other_fields: {merchant_feedbac..."